name       : folks
version    : 0.11.4
release    : 13
source     :
    - https://download.gnome.org/sources/folks/0.11/folks-0.11.4.tar.xz : a7b03ed30373e29f62fc3e6f498adce2d4909b852608fc2058a02fda9f80189a
license    : GPL-2.0-only
component  : desktop.gnome
summary    : GNOME metacontacts library
description: |
    Folks is a library that aggregates people from multiple sources (eg, Telepathy connection managers and eventually Evolution Data Server, Facebook, etc.) to create metacontacts.
builddeps  :
    - pkgconfig(evolution-data-server-1.2)
    - pkgconfig(gee-0.8)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libxml-2.0)
    - pkgconfig(telepathy-glib)
    - vala
setup      : |
    %configure --disable-static \
               --disable-fatal-warnings \
               --disable-tracker-backend \
               --enable-import-tool
build      : |
    %make
install    : |
    %make_install
