name       : folks
version    : 0.12.1
release    : 15
source     :
    - https://download.gnome.org/sources/folks/0.12/folks-0.12.1.tar.xz : 3ca9f2d50fdf5a7a3d3f59c49bd54ceaf8d8181938762370e07535f86d36d475
license    : GPL-2.0-only
component  : desktop.gnome
summary    : GNOME metacontacts library
description: |
    Folks is a library that aggregates people from multiple sources (eg, Telepathy connection managers and eventually Evolution Data Server, Facebook, etc.) to create metacontacts.
builddeps  :
    - pkgconfig(evolution-data-server-1.2)
    - pkgconfig(gee-0.8)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libxml-2.0)
    - pkgconfig(telepathy-glib)
    - vala
setup      : |
    %patch -p1 < $pkgfiles/0001-eds-Adapt-to-libebook-API-changes.patch
    %patch -p1 < $pkgfiles/0002-tests-Remove-errornous.patch
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
