name       : folks
version    : 0.11.3
release    : 10
source     :
    - http://ftp.gnome.org/pub/gnome/sources/folks/0.11/folks-0.11.3.tar.xz : 2a2828a7c87fd39e5786f8f2cf0ebe47576a74974f1355c478a6dc747d7bcb64
license    : GPL-2.0
component  : desktop.gnome
summary    : GNOME metacontacts library
description: |
    Folks is a library that aggregates people from multiple sources (eg, Telepathy connection managers and eventually Evolution Data Server, Facebook, etc.) to create metacontacts.
builddeps  :
    - pkgconfig(evolution-data-server-1.2)
    - pkgconfig(gee-0.8)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libxml-2.0)
    - pkgconfig(telepathy-glib)
    - vala
setup      : |
    %configure --disable-static \
               --disable-fatal-warnings \
               --disable-tracker-backend \
               --enable-import-tool
build      : |
    %make
install    : |
    %make_install
