name        : folks
version     : 0.11.2
release     : 7
source      :
    - http://ftp.gnome.org/pub/gnome/sources/folks/0.11/folks-0.11.2.tar.xz : 35a80a40e0cf68d5e86eff2ad55320f17427f66377c453ba5a1dbbd71755a1b8
license     : GPL-2.0
component   : desktop.gnome
summary     : GNOME metacontacts library
description : |
    Folks is a library that aggregates people from multiple sources (eg, Telepathy connection managers and eventually Evolution Data Server, Facebook, etc.) to create metacontacts.
builddeps   :
    - pkgconfig(evolution-data-server-1.2)
    - pkgconfig(gee-0.8)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libxml-2.0)
    - pkgconfig(telepathy-glib)
    - vala
setup      : |
    %configure --disable-static \
               --disable-fatal-warnings \
               --disable-tracker-backend \
               --enable-import-tool
build      : |
    %make
install    : |
    %make_install
