name        : folks
version     : 0.11.1
release     : 4
source     :
    - http://ftp.gnome.org/pub/gnome/sources/folks/0.11/folks-0.11.1.tar.xz : 6740d9074be911959904b40e7264d298bb5622995098ddfa1751dcd2bc4c917d
license     : GPL-2.0+
summary     : GNOME metacontacts library
builddeps   :
    - pkgconfig(gee-0.8)
    - pkgconfig(telepathy-glib)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libxml-2.0)
    - pkgconfig(evolution-data-server-1.2)
    - pkgconfig(libsecret-1)
    - vala
description : |
    Folks is a library that aggregates people from multiple sources (eg, Telepathy connection managers and eventually Evolution Data Server, Facebook, etc.) to create metacontacts.
setup      : |
    %configure --disable-static \
               --disable-fatal-warnings \
               --disable-tracker-backend
               --enable-telepathy-backend \
               --enable-tracker-backend \
               --enable-import-tool
build      : |
    %make
install    : |
    %make_install
