name       : folks
version    : 0.15.6
release    : 25
source     :
    - https://download.gnome.org/sources/folks/0.15/folks-0.15.6.tar.xz : c866630c553f29ce9be1c7a60267cb4080a6bccf4b8d551dc4c7e6234d840248
license    : GPL-2.0-only
component  : desktop.gnome
summary    : GNOME metacontacts library
description: |
    Folks is a library that aggregates people from multiple sources (eg, Telepathy connection managers and eventually Evolution Data Server, Facebook, etc.) to create metacontacts.
builddeps  :
    - pkgconfig(evolution-data-server-1.2)
    - pkgconfig(gee-0.8)
    - pkgconfig(libgdata)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libxml-2.0)
    - pkgconfig(telepathy-glib)
    - vala
setup      : |
    %meson_configure -Dtests=false
build      : |
    %ninja_build
install    : |
    %ninja_install
