name       : folks
version    : 0.15.3
release    : 21
source     :
    - https://download.gnome.org/sources/folks/0.15/folks-0.15.3.tar.xz : 21d737faf093f4be065473ee70ca20885b9a2c3685941dba24c2239fd3c544a5
license    : GPL-2.0-only
component  : desktop.gnome
summary    : GNOME metacontacts library
description: |
    Folks is a library that aggregates people from multiple sources (eg, Telepathy connection managers and eventually Evolution Data Server, Facebook, etc.) to create metacontacts.
builddeps  :
    - pkgconfig(evolution-data-server-1.2)
    - pkgconfig(gee-0.8)
    - pkgconfig(libgdata)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libxml-2.0)
    - pkgconfig(telepathy-glib)
    - vala
setup      : |
    %meson_configure -Dtests=false
build      : |
    %ninja_build
install    : |
    %ninja_install
