name       : folks
version    : 0.14.0
release    : 20
source     :
    - https://download.gnome.org/sources/folks/0.14/folks-0.14.0.tar.xz : d6e778da637d3b33fd9a6b45115e8157d8868211dc08b943d1075b5eb7282bb9
license    : GPL-2.0-only
component  : desktop.gnome
summary    : GNOME metacontacts library
description: |
    Folks is a library that aggregates people from multiple sources (eg, Telepathy connection managers and eventually Evolution Data Server, Facebook, etc.) to create metacontacts.
builddeps  :
    - pkgconfig(evolution-data-server-1.2)
    - pkgconfig(gee-0.8)
    - pkgconfig(libgdata)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libxml-2.0)
    - pkgconfig(telepathy-glib)
    - vala
setup      : |
    %patch -p1 < $pkgfiles/0001-Don-t-force-tests.patch
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
